# Generated by Django 3.2.5 on 2021-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=50)),
                ('vechtype', models.CharField(max_length=50)),
                ('vechnum', models.IntegerField()),
                ('servicetype', models.CharField(max_length=50)),
            ],
        ),
    ]
