# Generated by Django 3.2.5 on 2021-07-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='custname',
            new_name='customerName',
        ),
    ]
