# Generated by Django 3.2.5 on 2021-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210729_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='cutomerName',
            new_name='CUSTOMRNAME',
        ),
    ]
