# Generated by Django 3.2.5 on 2021-07-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_cutomername_show_customrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='CUSTOMRNAME',
            new_name='custname',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='VECHILETYPE',
            new_name='vechtype',
        ),
    ]
